name: AI Coder (manual)

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Describe what you want the AI to build"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  ai-coder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: Run AI Coder
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          TASK: ${{ inputs.task }}
        run: python tools/ai_coder.py

      - name: Show git status (did AI write files?)
        run: |
          git status --porcelain || true
          git diff --stat || true

      - name: Ensure at least one changed file
        run: |
          mkdir -p tools
          echo "run $GITHUB_RUN_ID" >> tools/.ai-keepalive.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ai/${{ github.run_id }}
          add-paths: |
            .
          commit-message: "ai: ${{ inputs.task }}"
          title: "AI: ${{ inputs.task }}"
          body: |
            This PR was generated by the AI Coder workflow.
            **Task:** ${{ inputs.task }}
          delete-branch: true
          draft: false

      - name: Print PR info
        if: always()
        run: |
          echo "pull-request-number=${{ steps.cpr.outputs.pull-request-number }}"
          echo "pull-request-url=${{ steps.cpr.outputs.pull-request-url }}"
