name: AI Coder (manual)

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Describe what you want the AI to build"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  ai-coder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: Run AI Coder
        id: ai
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          TASK: ${{ inputs.task }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: python tools/ai_coder.py

      # --- Validate any generated *-ci.yml workflows (optional, safe) ------
      - name: Validate any changed workflow files
        run: |
          set -e
          CHANGED=$(git ls-files -m -o --exclude-standard | grep -E '^\.github/workflows/.*-ci\.yml$' || true)
          if [ -z "$CHANGED" ]; then
            echo "No *-ci.yml workflow changes detected."
            exit 0
          fi

          echo "Changed workflow files:"
          echo "$CHANGED"

          # Install actionlint
          curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- -b .
          for f in $CHANGED; do
            echo "Validating $f"
            ./actionlint -color -shellcheck= -pyflakes= "$f"
          done
      # ---------------------------------------------------------------------

      - name: Ensure at least one changed file (always)
        run: |
          mkdir -p tools
          echo "run $GITHUB_RUN_ID $(date -u +%FT%TZ)" >> tools/.ai-keepalive.txt

      - name: Show what changed
        run: |
          echo "---- git status ----"; git status --porcelain || true
          echo "---- git diff --stat ----"; git diff --stat || true
          echo "---- ls -la top ----"; ls -la || true
          echo "AI step outcome: ${{ steps.ai.outcome }}"

      - name: Commit & push branch (always)
        env:
          BRANCH: ai/${{ github.run_id }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit; touching marker"
            echo "touch $(date -u +%FT%TZ)" >> tools/.ai-touch.txt
            git add tools/.ai-touch.txt
          fi
          git commit -m "ai: ${{ inputs.task }}"
          git push origin "$BRANCH"

      - name: Open PR
        uses: actions/github-script@v7
        id: pr
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = `ai/${process.env.GITHUB_RUN_ID}`;
            const res = await github.rest.pulls.create({
              owner,
              repo,
              title: `AI: ${{ inputs.task }}`,
              head: branch,
              base: 'main',
              body: `This PR was generated by the AI Coder workflow.\n\n**Task:** ${{ inputs.task }}\n\nAI step outcome: ${ context.steps?.ai?.outcome ?? 'unknown' }`
            });
            core.setOutput('url', res.data.html_url);

      - name: Print PR URL
        run: echo "pull-request-url=${{ steps.pr.outputs.url }}"
