name: AI Coder (manual)

on:
  workflow_dispatch:
    inputs:
      task:
        description: "Describe what you want the AI to build"
        required: true

permissions:
  contents: write
  pull-requests: write
  actions: read
  # workflows: write  # uncomment only if you need to manage workflows via API

concurrency:
  group: ai-coder-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ai-coder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: Run AI Coder
        id: ai
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          TASK: ${{ inputs.task }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          set -euo pipefail
          python tools/ai_coder.py

      # --- Validate any generated *-ci.yml workflows ------------------------
      - name: Validate any changed workflow files
        shell: bash
        run: |
          set -euo pipefail
          CHANGED=$(git ls-files -m -o --exclude-standard | grep -E '^\.github/workflows/.*-ci\.ya?ml$' || true)
          if [ -z "$CHANGED" ]; then
            echo "No *-ci.yml workflow changes detected."
            exit 0
          fi

          echo "Changed workflow files:"
          echo "$CHANGED"

          curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- -b .
          for f in $CHANGED; do
            echo "Validating $f"
            ./actionlint -color -shellcheck= -pyflakes= "$f"
          done
      # ---------------------------------------------------------------------

      - name: Ensure at least one changed file (always)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p tools
          echo "run $GITHUB_RUN_ID $(date -u +%FT%TZ)" >> tools/.ai-keepalive.txt

      - name: Show what changed
        shell: bash
        run: |
          set -euo pipefail
          echo "---- git status ----"; git status --porcelain || true
          echo "---- git diff --stat ----"; git diff --stat || true
          echo "AI step outcome: ${{ steps.ai.outcome }}"

      - name: Commit & push branch (always)
        shell: bash
        env:
          BRANCH: ai/${{ github.run_id }}
          TASK_INPUT: ${{ inputs.task }}
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit; touching marker"
            echo "touch $(date -u +%FT%TZ)" >> tools/.ai-touch.txt
            git add tools/.ai-touch.txt
          fi
          # Write the commit message to a file to avoid quoting issues
          printf "ai: %s\n" "$TASK_INPUT" > /tmp/COMMIT_MSG.txt
          git commit -F /tmp/COMMIT_MSG.txt
          git push origin "$BRANCH"

      - name: Open PR
        uses: actions/github-script@v7
        id: pr
        env:
          TASK_INPUT: ${{ inputs.task }}
          AI_OUTCOME: ${{ steps.ai.outcome }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = `ai/${process.env.GITHUB_RUN_ID}`;
            const raw = process.env.TASK_INPUT || '';
            const titleLine = raw.split('\n')[0].replace(/\r/g, '').slice(0, 70);
            const body = [
              'This PR was generated by the AI Coder workflow.',
              '',
              '**Task (raw):**',
              '```',
              raw,
              '```',
              `AI step outcome: ${process.env.AI_OUTCOME || 'unknown'}`
            ].join('\n');
            const res = await github.rest.pulls.create({
              owner, repo,
              title: `AI: ${titleLine}`,
              head: branch,
              base: 'main',
              body
            });
            core.setOutput('url', res.data.html_url);

      - name: Print PR URL
        shell: bash
        run: echo "pull-request-url=${{ steps.pr.outputs.url }}"
