name: Media CI
on:
  pull_request:
    paths: ["apps/media/**", ".github/workflows/media-ci.yml"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install --upgrade pip
      - run: |
          cd apps/media
          python -m venv .venv
          . .venv/bin/activate
          pip install fastapi uvicorn pytest
      - run: |
          cd apps/media
          . .venv/bin/activate
          pytest -q
