name: Smoke PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make a change
        run: |
          mkdir -p tools
          echo "smoke $(date -u +%FT%TZ)" >> tools/.smoke.txt
          git status --porcelain
          git diff --stat

      - name: Commit & push branch
        env:
          BRANCH: smoke/${{ github.run_id }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add -A
          git commit -m "smoke: touch marker"
          git push origin "$BRANCH"

      - name: Open PR
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const head = `smoke/${process.env.GITHUB_RUN_ID}`;
            const res = await github.rest.pulls.create({
              owner, repo,
              title: `Smoke PR ${process.env.GITHUB_RUN_ID}`,
              head, base: 'main',
              body: 'This is a smoke test PR created without AI.'
            });
            core.setOutput('url', res.data.html_url);

      - name: Print PR URL
        run: echo "${{ steps.github-script.outputs.url }}"
